#!/usr/bin/bash

# REQUIRES: a shell, coreutils, libnotify, a notification daemon, waybar, psmisc

# a script to switch between the two mpd server I am running
# it is very setup specific and performs some unnecessary actions
# (I do those just out of correctness, I guess)

# it links the proper mpd files to their usual spots
# it links two different waybar configs so it reads from the right server
# (haven't found a better solution yet)

# ALSO, most importantly, it writes to the .currentport file which my other script, currentmpc uses

rm_links() {
	unlink "$HOME/.mpd/database"
	unlink "$HOME/.mpd/playlists"
	unlink "$HOME/.mpd/pid"
	unlink "$HOME/.mpd/state"

	unlink "$XDG_CONFIG_HOME/waybar/config.jsonc"
}

create_links() {
	ln -s "$HOME/.mpd/$1database" "$HOME/.mpd/database"
	ln -s "$HOME/.mpd/$1pid" "$HOME/.mpd/pid"
	ln -s "$HOME/.mpd/$1playlist" "$HOME/.mpd/playlists"
	ln -s "$HOME/.mpd/$1state" "$HOME/.mpd/state"

	ln -s "$XDG_CONFIG_HOME/waybar/$1config.jsonc" "$XDG_CONFIG_HOME/waybar/config.jsonc"
}

notify() {
        notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "$1"
}

if [[ "$1" == "--get" ]]; then
	if [[ "$(cat "$XDG_CONFIG_HOME/mpd/.currentport")" == "6600" ]]; then
		echo "Using normal MPD on port $(cat "$XDG_CONFIG_HOME/config/mpd/.currentport")"
	else
		echo "Using album/other MPD on port $(cat "$XDG_CONFIG_HOME/mpd/.currentport")"
	fi
	exit
fi

rm_links

if [[ "$(cat $XDG_CONFIG_HOME/mpd/.currentport)" == "6600" ]]; then
	myport=6601
	create_links 'a'
	output="Switched to albums MPD"
else
	myport=6600
	create_links 'p'
	output="Switched to normal MPD"
fi
killall -SIGUSR2 waybar

echo "$myport" > "$XDG_CONFIG_HOME/mpd/.currentport"
if [[ "$1" == "--notify" ]]; then
	notify "$output"
fi
echo "$output"
